### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ElizabethYupyy** [CrystalVapor/Crystal-Recoil-System#3]
'set recoil pattern' not working from BP, when is called it's causing engine crash ;-(

Assertion failed: RecoilInterface [File:D:\Projects\rtr\Plugins\Crystal-Recoil-System-main\Source\CrystalRecoil\Private\CRRecoilComponent.cpp] [Line: 119]

UnrealEditor_CrystalRecoil!UCRRecoilComponent::TickComponent() [D:\Projects\rtr\Plugins\Crystal-Recoil-System-main\Source\CrystalRecoil\Private\CRRecoilComponent.cpp:28]
UnrealEditor_Engine
UnrealEditor_Engine

**Comment by CrystalVapor** [comment]
The assert as following:
![image](https://github.com/user-attachments/assets/ea4da8d6-5e39-47ce-8a63-5b4c5adc6489)
Seems you didn't inherit the ICRRecoilInterface for you pawn that owns recoil component, note this must be done in cpp.
(i actually expect this can be done in bp, but an interface who has a Bpcallable function cannot be a blueprintimplementable interface)

**Comment by ElizabethYupyy** [comment]
do you have any tutorials for inherit interface?... i am new in unreal and don't really know how to do that ;((

**Comment by CrystalVapor** [comment]
Sure!
Actually, inherit is a OOP concept which means make one child class for this class
In c++, just make your pawn directly inherit ICRRecoilInterface like this ( I assumed that you've know how to create c++ class and make your BP class inherit from that, there's many tutorials on youtube or ect can help you with that):
![image](https://github.com/user-attachments/assets/51095e3c-5043-4abc-82f1-bf5a690cb6d6)

but for my own project, situation's more complex, I inherit this interface on FIREARM Actor(which will be hold on player's hand, and related with display logic like recoil, VFX, sounds and etc..), and i implement functions like these:
![image](https://github.com/user-attachments/assets/c880f852-52a5-4c03-b55d-0d8da6a0280d)
![image](https://github.com/user-attachments/assets/e4cbfbf7-a459-420e-bb09-b72c794e3da5)
as you can see, the target controller's expected to be player's controller, and recoilComponent should be the component who have correct recoil pattern

Unfortunately, i designed this plugin for c++, for now you can only implement these two function in c++, i will try to perform some work on it to make this plugin's 100% BP-accessible, but that may takes a few days if possible...

**Comment by ElizabethYupyy** [comment]
Thank u! i am little dumb, what i am doing wrong?... 
![image](https://github.com/user-attachments/assets/a9317e33-8218-4809-8a0c-52fa831ada74)

**Comment by CrystalVapor** [comment]
Hi!
Seems you are really new to c++ or other programming language I guess...?
The error message intends that RecoilComponent is not defined as a part of your class, i mean you've probably defined it in Blueprint but the cpp class is parent class of your blueprint class, so when we've compiling your cpp class, there's no component named RecoilComponent!
You may need to spawn RecoilComponent in your cpp class rather than Blueprint(also many tutorials about that)
Hope these information can help you!

**Comment by ElizabethYupyy** [comment]
Thank u for help! i will try. (Yep, i am really new)
but please don't quit this recoil plugin ;D it's really good and i will wait bp version! thank u again!

**Comment by CrystalVapor** [comment]
Hi I'm fristly trying to edit this plugin so it now can be 100% blueprint assceesible( I guess, XD)
You can now simply implements the interface in your blueprint class editor( Class Settings->Interfaces->Implemented->Add)
![image](https://github.com/user-attachments/assets/625f30d9-9fc0-453e-be65-b20c7db8808f)
(I'm chinese, so just ignore my GUI Language XD)
And override the function in BluePrint
![image](https://github.com/user-attachments/assets/4206360e-128b-402f-ac61-201c9aa3b8ff)
(You can First find this two functions in Interfaces List, but i've override them)
![image](https://github.com/user-attachments/assets/ec6c915a-3071-42b7-974f-b6b6796b8226)
![image](https://github.com/user-attachments/assets/6bcb1ac5-0fef-48d6-b095-e02a2aebce68)
I've tested this, it works as i thought.
I will upload this commit later when i fix IsDataValid()'s deprecated problem   (|ovo|)
